on:
  workflow_dispatch:

name: CI Real Device Test
jobs:
  e2e:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Run e2e tests
        run: go test -tags=e2e -count=1 -v ./test/e2e/...
